package fr.leboncoin.boundaries;

import fr.leboncoin.daos.Csv2BD;
import fr.leboncoin.preparations.CategoriesProduitsAffinees2BD;

/**
 *
 * @author formation
 */
public class JIFCSV2BD extends javax.swing.JInternalFrame {

    private String isAction;

    /**
     *
     * @param psTitre
     */
    public JIFCSV2BD(String psTitre) {
        initComponents();

        setTitle("Import " + psTitre);
        isAction = psTitre;

        jButtonImporter.setText("Importer " + psTitre);

        setVisible(true);

    } /// Constructeur

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonImporter = new javax.swing.JButton();
        jLabelMessage = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("CSV 2 BD");

        jButtonImporter.setText("Importer ...");
        jButtonImporter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImporterActionPerformed(evt);
            }
        });

        jLabelMessage.setText("Message");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonImporter, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                    .addComponent(jLabelMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButtonImporter)
                .addGap(18, 18, 18)
                .addComponent(jLabelMessage)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonImporterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImporterActionPerformed
        String lsMessage = "";

        if (isAction.equalsIgnoreCase("pays")) {
            System.out.println("pays");
            lsMessage = Csv2BD.paysCsv2BD();
        }
        if (isAction.equalsIgnoreCase("régions")) {
            System.out.println("Régions");
            lsMessage = Csv2BD.regionsCsv2BD();
        }
        if (isAction.equalsIgnoreCase("départements")) {
            System.out.println("Départements");
            lsMessage = Csv2BD.departementsCsv2BD();
        }
        if (isAction.equalsIgnoreCase("villes")) {
            System.out.println("Villes");
            lsMessage = Csv2BD.villesCsv2BD();
        }
        if (isAction.equalsIgnoreCase("catégories")) {
            System.out.println("Catégories");
//            lsMessage = Csv2BD.categoriesCsv2BD();
            boolean lbOK = CategoriesProduitsAffinees2BD.importations();
            if (lbOK) {
                lsMessage = "Transfert OK";
            } else {
                lsMessage = "Transfert KO";
            }
        }

        jLabelMessage.setText(lsMessage);
    }//GEN-LAST:event_jButtonImporterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonImporter;
    private javax.swing.JLabel jLabelMessage;
    // End of variables declaration//GEN-END:variables
}
