package fr.leboncoin.boundaries;

import fr.leboncoin.Globale;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.*;

/**
 *
 * @author pascal
 */
public class JIFDepartementCRUD extends javax.swing.JInternalFrame {

    private DefaultTableModel idtm;
    private Connection icn;
    private Map<String, String> mapRegionsIdNom = new HashMap();
    private Map<String, String> mapRegionsNomId = new HashMap();

    /**
     * Creates new form JIFProduitsCRUD
     */
    public JIFDepartementCRUD() {
        initComponents();

        setTitle("Départements");
        jLabelMessage.setText("");
        jTextFieldIdRegion.setEnabled(false);

        icn = Globale.getCn();
        remplirJTableEtJCombo();

        jTableDepartements.getColumn("ID Département").setMaxWidth(0);
        jTableDepartements.getColumn("ID Département").setWidth(0);
        jTableDepartements.getColumn("ID Département").setMinWidth(0);

        setVisible(true);

    } /// JIFDepartementCRUD

    /**
     *
     */
    private void remplirJTableEtJCombo() {
        try {

            idtm = (DefaultTableModel) jTableDepartements.getModel();

            Object[] tLigne;

            PreparedStatement lpst = icn.prepareStatement("CALL departementSelectAll()");
            ResultSet lrs = lpst.executeQuery();

            while (lrs.next()) {
                tLigne = new Object[4];
                for (int i = 0; i < tLigne.length; i++) {
                    // JTable
                    tLigne[0] = lrs.getString(1); // ID DEPT
                    tLigne[1] = lrs.getString(4); // NOM
                    tLigne[2] = lrs.getString(3); // CODE
                    tLigne[3] = lrs.getString(2); // ID REGION

                }

                idtm.addRow(tLigne);
            }

            lrs.close();
            lpst.close();

            /*
             REGION
             */
            // ID REGION, ID PAYS, NOM REGION, CODE REGION
            lpst = icn.prepareStatement("CALL regionSelectAll()");
            lrs = lpst.executeQuery();

            while (lrs.next()) {
                jComboBoxRegions.addItem(lrs.getString(3));

                mapRegionsIdNom.put(lrs.getString(1), lrs.getString(3));
                mapRegionsNomId.put(lrs.getString(3), lrs.getString(1));
            }

            lrs.close();
            lpst.close();

            //jLabelMessage.setText("Jusque là tout va bien !!!");
        } catch (SQLException ex) {
            jLabelMessage.setText(ex.getMessage());
        }
    } /// remplirJTable

    /**
     *
     */
    private void viderJTable() {
        for (int i = idtm.getRowCount() - 1; i >= 0; i--) {
            idtm.removeRow(i);
        }
    } /// viderJTable

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMessage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDepartements = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelIdDepartement = new javax.swing.JLabel();
        jTextFieldNomDuDepartement = new javax.swing.JTextField();
        jTextFieldCodeDepartement = new javax.swing.JTextField();
        jTextFieldIdRegion = new javax.swing.JTextField();
        jButtonAjouter = new javax.swing.JButton();
        jButtonModifier = new javax.swing.JButton();
        jButtonSupprimer = new javax.swing.JButton();
        jButtonRafraichir = new javax.swing.JButton();
        jButtonCLS = new javax.swing.JButton();
        jComboBoxRegions = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabelMessage.setText("Message");

        jTableDepartements.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Département", "Nom du département", "Code du département", "ID Région"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDepartements.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDepartementsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDepartements);

        jLabel2.setText("ID département");

        jLabel3.setText("Nom du département");

        jLabel4.setText("Code département");

        jLabel5.setText("Id Région");

        jLabelIdDepartement.setForeground(new java.awt.Color(255, 0, 51));
        jLabelIdDepartement.setText("ID");

        jTextFieldNomDuDepartement.setText("Zéro");

        jTextFieldCodeDepartement.setText("999");

        jTextFieldIdRegion.setText("1");

        jButtonAjouter.setText("Ajouter");
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });

        jButtonModifier.setText("Modifier");
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });

        jButtonSupprimer.setText("Supprimer");
        jButtonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerActionPerformed(evt);
            }
        });

        jButtonRafraichir.setText("Rafraîchir");
        jButtonRafraichir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRafraichirActionPerformed(evt);
            }
        });

        jButtonCLS.setText("CLS");
        jButtonCLS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCLSActionPerformed(evt);
            }
        });

        jComboBoxRegions.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBoxRegionsPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBoxRegionsPopupMenuWillBecomeVisible(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                    .addComponent(jLabelMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonCLS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonAjouter))
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNomDuDepartement)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelIdDepartement, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCodeDepartement, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonModifier)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonSupprimer)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonRafraichir)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldIdRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxRegions, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelIdDepartement))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomDuDepartement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldCodeDepartement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldIdRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxRegions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCLS)
                    .addComponent(jButtonAjouter)
                    .addComponent(jButtonModifier)
                    .addComponent(jButtonSupprimer)
                    .addComponent(jButtonRafraichir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabelMessage)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed
        try {
            PreparedStatement lpst = icn.prepareStatement("CALL departementInsert(?,?,?,?)");
            lpst.setInt(1, 0);
            lpst.setString(2, jTextFieldIdRegion.getText());
            lpst.setString(3, jTextFieldCodeDepartement.getText());
            lpst.setString(4, jTextFieldNomDuDepartement.getText());

            lpst.executeUpdate();
            icn.commit();
            jLabelMessage.setText("Nouveau département ajouté !");
        } catch (SQLException e) {
            jLabelMessage.setText(e.getMessage());
        }
    }//GEN-LAST:event_jButtonAjouterActionPerformed

    private void jButtonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerActionPerformed
        try {
            PreparedStatement lpst = icn.prepareStatement("CALL departementDelete(?)");
            lpst.setInt(1, Integer.valueOf(jLabelIdDepartement.getText()));
            lpst.executeUpdate();
            icn.commit();
            jLabelMessage.setText("Département supprimé !");
        } catch (SQLException e) {
            jLabelMessage.setText(e.getMessage());
        }
    }//GEN-LAST:event_jButtonSupprimerActionPerformed

    private void jTableDepartementsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDepartementsMouseClicked
        //
        jLabelIdDepartement.setText(jTableDepartements.getValueAt(jTableDepartements.getSelectedRow(), 0).toString());
        jTextFieldNomDuDepartement.setText(jTableDepartements.getValueAt(jTableDepartements.getSelectedRow(), 1).toString());
        jTextFieldCodeDepartement.setText(jTableDepartements.getValueAt(jTableDepartements.getSelectedRow(), 2).toString());
        jTextFieldIdRegion.setText(jTableDepartements.getValueAt(jTableDepartements.getSelectedRow(), 3).toString());

        // Actualisation de la combo 
        jComboBoxRegions.setSelectedItem(mapRegionsIdNom.get(jTextFieldIdRegion.getText()));

    }//GEN-LAST:event_jTableDepartementsMouseClicked

    private void jButtonRafraichirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRafraichirActionPerformed
        //
        viderJTable();
        remplirJTableEtJCombo();
        jLabelMessage.setText("");
    }//GEN-LAST:event_jButtonRafraichirActionPerformed

    private void jButtonCLSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCLSActionPerformed
        //
        this.jLabelIdDepartement.setText("");
        this.jTextFieldNomDuDepartement.setText("");
        this.jTextFieldCodeDepartement.setText("");
        this.jTextFieldIdRegion.setText("");
    }//GEN-LAST:event_jButtonCLSActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosing

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
        try {
            // ID dept, ID region, Code dept, Nom dept
            PreparedStatement lpst = icn.prepareStatement("CALL departementUpdate(?,?,?,?)");
            lpst.setInt(1, Integer.valueOf(jLabelIdDepartement.getText()));
            lpst.setString(2, jTextFieldIdRegion.getText());
            lpst.setString(3, jTextFieldCodeDepartement.getText());
            lpst.setString(4, jTextFieldNomDuDepartement.getText());
            lpst.executeUpdate();
            icn.commit();
            jLabelMessage.setText("Département modifié !");
        } catch (SQLException e) {
            jLabelMessage.setText(e.getMessage());
        }
    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void jComboBoxRegionsPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBoxRegionsPopupMenuWillBecomeVisible
        // 

    }//GEN-LAST:event_jComboBoxRegionsPopupMenuWillBecomeVisible

    private void jComboBoxRegionsPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBoxRegionsPopupMenuWillBecomeInvisible
        // Quand la liste de la combo se ferme
        jTextFieldIdRegion.setText(mapRegionsNomId.get(jComboBoxRegions.getSelectedItem().toString()));
    }//GEN-LAST:event_jComboBoxRegionsPopupMenuWillBecomeInvisible


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JButton jButtonCLS;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonRafraichir;
    private javax.swing.JButton jButtonSupprimer;
    private javax.swing.JComboBox jComboBoxRegions;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelIdDepartement;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDepartements;
    private javax.swing.JTextField jTextFieldCodeDepartement;
    private javax.swing.JTextField jTextFieldIdRegion;
    private javax.swing.JTextField jTextFieldNomDuDepartement;
    // End of variables declaration//GEN-END:variables
}
