package fr.leboncoin.boundaries;

import fr.leboncoin.Globale;
import javax.swing.table.DefaultTableModel;
import java.sql.*;

/**
 *
 * @author pascal
 */
public class JIFPaysCRUD extends javax.swing.JInternalFrame {

    private DefaultTableModel idtm;
    private Connection icn;

    /**
     * Creates new form JIFProduitsCRUD
     */
    public JIFPaysCRUD() {
        initComponents();

        setTitle("Pays");
        jLabelMessage.setText("");

        icn = Globale.getCn();
        remplirJTable();

        jTablePays.getColumn("ID Pays").setMaxWidth(0);
        jTablePays.getColumn("ID Pays").setWidth(0);
        jTablePays.getColumn("ID Pays").setMinWidth(0);

        setVisible(true);

    } /// JIFPaysCRUD

    /**
     *
     */
    private void remplirJTable() {
        try {

            idtm = (DefaultTableModel) jTablePays.getModel();

            Object[] tLigne;

            // ID pays, nom pays, code, code iso3
            PreparedStatement lpst = icn.prepareStatement("CALL paysSelectAll()");
            ResultSet lrs = lpst.executeQuery();
            while (lrs.next()) {
                tLigne = new Object[4];
                for (int i = 0; i < tLigne.length; i++) {
                    tLigne[i] = lrs.getString(i + 1);
                }

                idtm.addRow(tLigne);
            }
            lrs.close();
            lpst.close();

            //jLabelMessage.setText("Jusque là tout va bien !!!");
        } catch (SQLException ex) {
            jLabelMessage.setText(ex.getMessage());
        }
    } /// remplirJTable

    /**
     *
     */
    private void viderJTable() {
        for (int i = idtm.getRowCount() - 1; i >= 0; i--) {
            idtm.removeRow(i);
        }
    } /// viderJTable

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMessage = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePays = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelIdPays = new javax.swing.JLabel();
        jTextFieldNomDuPays = new javax.swing.JTextField();
        jTextFieldCodePays = new javax.swing.JTextField();
        jTextFieldCodeISO3 = new javax.swing.JTextField();
        jButtonAjouter = new javax.swing.JButton();
        jButtonModifier = new javax.swing.JButton();
        jButtonSupprimer = new javax.swing.JButton();
        jButtonRafraichir = new javax.swing.JButton();
        jButtonCLS = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabelMessage.setText("Message");

        jTablePays.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Pays", "Nom du pays", "Code du pays", "Code ISO3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePays.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePaysMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePays);

        jLabel2.setText("ID pays");

        jLabel3.setText("Nom du pays");

        jLabel4.setText("Code pays");

        jLabel5.setText("Code ISO3");

        jLabelIdPays.setForeground(new java.awt.Color(255, 0, 51));
        jLabelIdPays.setText("ID");

        jTextFieldNomDuPays.setText("Zéro");

        jTextFieldCodePays.setText("00000");

        jTextFieldCodeISO3.setText("000");

        jButtonAjouter.setText("Ajouter");
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });

        jButtonModifier.setText("Modifier");
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });

        jButtonSupprimer.setText("Supprimer");
        jButtonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerActionPerformed(evt);
            }
        });

        jButtonRafraichir.setText("Rafraîchir");
        jButtonRafraichir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRafraichirActionPerformed(evt);
            }
        });

        jButtonCLS.setText("CLS");
        jButtonCLS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCLSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                    .addComponent(jLabelMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonCLS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonAjouter))
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIdPays, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCodeISO3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonModifier)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonSupprimer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonRafraichir))
                            .addComponent(jTextFieldCodePays, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNomDuPays, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelIdPays))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomDuPays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldCodePays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldCodeISO3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCLS)
                    .addComponent(jButtonAjouter)
                    .addComponent(jButtonModifier)
                    .addComponent(jButtonSupprimer)
                    .addComponent(jButtonRafraichir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabelMessage)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed
        try {
            PreparedStatement lpst = icn.prepareStatement("CALL paysInsert(?,?,?,?)");
            lpst.setInt(1, 0);
            lpst.setString(2, jTextFieldNomDuPays.getText());
            lpst.setString(3, jTextFieldCodePays.getText());
            lpst.setString(4, jTextFieldCodeISO3.getText());
            lpst.executeUpdate();
            icn.commit();
            jLabelMessage.setText("Nouveau pays ajouté !");
        } catch (SQLException e) {
            jLabelMessage.setText(e.getMessage());
        }
    }//GEN-LAST:event_jButtonAjouterActionPerformed

    private void jButtonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerActionPerformed
        try {
            PreparedStatement lpst = icn.prepareStatement("CALL paysDelete(?)");
            lpst.setInt(1, Integer.valueOf(jLabelIdPays.getText()));
            lpst.executeUpdate();
            icn.commit();
            jLabelMessage.setText("Pays supprimé !");
        } catch (SQLException e) {
            jLabelMessage.setText(e.getMessage());
        }
    }//GEN-LAST:event_jButtonSupprimerActionPerformed

    private void jTablePaysMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePaysMouseClicked
        //
        jLabelIdPays.setText(jTablePays.getValueAt(jTablePays.getSelectedRow(), 0).toString());
        jTextFieldNomDuPays.setText(jTablePays.getValueAt(jTablePays.getSelectedRow(), 1).toString());
        jTextFieldCodePays.setText(jTablePays.getValueAt(jTablePays.getSelectedRow(), 2).toString());
        jTextFieldCodeISO3.setText(jTablePays.getValueAt(jTablePays.getSelectedRow(), 3).toString());

    }//GEN-LAST:event_jTablePaysMouseClicked

    private void jButtonRafraichirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRafraichirActionPerformed
        //
        viderJTable();
        remplirJTable();
        jLabelMessage.setText("");
    }//GEN-LAST:event_jButtonRafraichirActionPerformed

    private void jButtonCLSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCLSActionPerformed
        //
        this.jLabelIdPays.setText("");
        this.jTextFieldNomDuPays.setText("");
        this.jTextFieldCodePays.setText("");
        this.jTextFieldCodeISO3.setText("");
    }//GEN-LAST:event_jButtonCLSActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameClosing

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
        try {
            PreparedStatement lpst = icn.prepareStatement("CALL paysUpdate(?,?,?,?)");
            lpst.setInt(1, Integer.valueOf(jLabelIdPays.getText()));
            lpst.setString(2, jTextFieldNomDuPays.getText());
            lpst.setString(3, jTextFieldCodePays.getText());
            lpst.setString(4, jTextFieldCodeISO3.getText());
            lpst.executeUpdate();
            icn.commit();
            jLabelMessage.setText("Pays modifié !");
        } catch (SQLException e) {
            jLabelMessage.setText(e.getMessage());
        }
    }//GEN-LAST:event_jButtonModifierActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JButton jButtonCLS;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonRafraichir;
    private javax.swing.JButton jButtonSupprimer;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelIdPays;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePays;
    private javax.swing.JTextField jTextFieldCodeISO3;
    private javax.swing.JTextField jTextFieldCodePays;
    private javax.swing.JTextField jTextFieldNomDuPays;
    // End of variables declaration//GEN-END:variables
}
